// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActType int32

const (
	ActType_ACT_UNKNOWN  ActType = 0
	ActType_ACT_JOIN     ActType = 1
	ActType_ACT_QUIT     ActType = 2
	ActType_ACT_WITHDRAW ActType = 3
	ActType_ACT_SYNC     ActType = 4
	ActType_ACT_RENAME   ActType = 5
	ActType_ACT_CREATE   ActType = 6
	ActType_ACT_SESSION  ActType = 7
	ActType_ACT_SESSIONS ActType = 8
	ActType_ACT_MEMBERS  ActType = 9
	ActType_ACT_MESSAGES ActType = 10
)

var ActType_name = map[int32]string{
	0:  "ACT_UNKNOWN",
	1:  "ACT_JOIN",
	2:  "ACT_QUIT",
	3:  "ACT_WITHDRAW",
	4:  "ACT_SYNC",
	5:  "ACT_RENAME",
	6:  "ACT_CREATE",
	7:  "ACT_SESSION",
	8:  "ACT_SESSIONS",
	9:  "ACT_MEMBERS",
	10: "ACT_MESSAGES",
}

var ActType_value = map[string]int32{
	"ACT_UNKNOWN":  0,
	"ACT_JOIN":     1,
	"ACT_QUIT":     2,
	"ACT_WITHDRAW": 3,
	"ACT_SYNC":     4,
	"ACT_RENAME":   5,
	"ACT_CREATE":   6,
	"ACT_SESSION":  7,
	"ACT_SESSIONS": 8,
	"ACT_MEMBERS":  9,
	"ACT_MESSAGES": 10,
}

func (x ActType) String() string {
	return proto.EnumName(ActType_name, int32(x))
}

func (ActType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{0}
}

type Action struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RemoteAddr           string   `protobuf:"bytes,2,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	RequestId            int64    `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Type                 ActType  `protobuf:"varint,5,opt,name=type,proto3,enum=rpc.ActType" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Action) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Action) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Action) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Action) GetType() ActType {
	if m != nil {
		return m.Type
	}
	return ActType_ACT_UNKNOWN
}

func (m *Action) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateSessionAction struct {
	SessionId            int64       `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	OwnerId              int64       `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UserIds              []int64     `protobuf:"varint,4,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	Type                 SessionType `protobuf:"varint,5,opt,name=type,proto3,enum=rpc.SessionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSessionAction) Reset()         { *m = CreateSessionAction{} }
func (m *CreateSessionAction) String() string { return proto.CompactTextString(m) }
func (*CreateSessionAction) ProtoMessage()    {}
func (*CreateSessionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{1}
}

func (m *CreateSessionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionAction.Unmarshal(m, b)
}
func (m *CreateSessionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionAction.Marshal(b, m, deterministic)
}
func (m *CreateSessionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionAction.Merge(m, src)
}
func (m *CreateSessionAction) XXX_Size() int {
	return xxx_messageInfo_CreateSessionAction.Size(m)
}
func (m *CreateSessionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionAction.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionAction proto.InternalMessageInfo

func (m *CreateSessionAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateSessionAction) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *CreateSessionAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSessionAction) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *CreateSessionAction) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_SESSION_UNKNOWN
}

type JoinSessionAction struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSessionAction) Reset()         { *m = JoinSessionAction{} }
func (m *JoinSessionAction) String() string { return proto.CompactTextString(m) }
func (*JoinSessionAction) ProtoMessage()    {}
func (*JoinSessionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{2}
}

func (m *JoinSessionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSessionAction.Unmarshal(m, b)
}
func (m *JoinSessionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSessionAction.Marshal(b, m, deterministic)
}
func (m *JoinSessionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSessionAction.Merge(m, src)
}
func (m *JoinSessionAction) XXX_Size() int {
	return xxx_messageInfo_JoinSessionAction.Size(m)
}
func (m *JoinSessionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSessionAction.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSessionAction proto.InternalMessageInfo

func (m *JoinSessionAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *JoinSessionAction) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type QuitSessionAction struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitSessionAction) Reset()         { *m = QuitSessionAction{} }
func (m *QuitSessionAction) String() string { return proto.CompactTextString(m) }
func (*QuitSessionAction) ProtoMessage()    {}
func (*QuitSessionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{3}
}

func (m *QuitSessionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitSessionAction.Unmarshal(m, b)
}
func (m *QuitSessionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitSessionAction.Marshal(b, m, deterministic)
}
func (m *QuitSessionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitSessionAction.Merge(m, src)
}
func (m *QuitSessionAction) XXX_Size() int {
	return xxx_messageInfo_QuitSessionAction.Size(m)
}
func (m *QuitSessionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitSessionAction.DiscardUnknown(m)
}

var xxx_messageInfo_QuitSessionAction proto.InternalMessageInfo

func (m *QuitSessionAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *QuitSessionAction) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type WithdrawMessageAction struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	MessageId            int64    `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawMessageAction) Reset()         { *m = WithdrawMessageAction{} }
func (m *WithdrawMessageAction) String() string { return proto.CompactTextString(m) }
func (*WithdrawMessageAction) ProtoMessage()    {}
func (*WithdrawMessageAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{4}
}

func (m *WithdrawMessageAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawMessageAction.Unmarshal(m, b)
}
func (m *WithdrawMessageAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawMessageAction.Marshal(b, m, deterministic)
}
func (m *WithdrawMessageAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawMessageAction.Merge(m, src)
}
func (m *WithdrawMessageAction) XXX_Size() int {
	return xxx_messageInfo_WithdrawMessageAction.Size(m)
}
func (m *WithdrawMessageAction) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawMessageAction.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawMessageAction proto.InternalMessageInfo

func (m *WithdrawMessageAction) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WithdrawMessageAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *WithdrawMessageAction) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type SyncMessageAction struct {
	DeviceId             int64      `protobuf:"varint,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncMessageAction) Reset()         { *m = SyncMessageAction{} }
func (m *SyncMessageAction) String() string { return proto.CompactTextString(m) }
func (*SyncMessageAction) ProtoMessage()    {}
func (*SyncMessageAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{5}
}

func (m *SyncMessageAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageAction.Unmarshal(m, b)
}
func (m *SyncMessageAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageAction.Marshal(b, m, deterministic)
}
func (m *SyncMessageAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageAction.Merge(m, src)
}
func (m *SyncMessageAction) XXX_Size() int {
	return xxx_messageInfo_SyncMessageAction.Size(m)
}
func (m *SyncMessageAction) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageAction.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageAction proto.InternalMessageInfo

func (m *SyncMessageAction) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SyncMessageAction) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type RenameSessionAction struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameSessionAction) Reset()         { *m = RenameSessionAction{} }
func (m *RenameSessionAction) String() string { return proto.CompactTextString(m) }
func (*RenameSessionAction) ProtoMessage()    {}
func (*RenameSessionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{6}
}

func (m *RenameSessionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameSessionAction.Unmarshal(m, b)
}
func (m *RenameSessionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameSessionAction.Marshal(b, m, deterministic)
}
func (m *RenameSessionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameSessionAction.Merge(m, src)
}
func (m *RenameSessionAction) XXX_Size() int {
	return xxx_messageInfo_RenameSessionAction.Size(m)
}
func (m *RenameSessionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameSessionAction.DiscardUnknown(m)
}

var xxx_messageInfo_RenameSessionAction proto.InternalMessageInfo

func (m *RenameSessionAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RenameSessionAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetMessagesAction struct {
	Session              int64      `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Cond                 string     `protobuf:"bytes,2,opt,name=cond,proto3" json:"cond,omitempty"`
	Messages             []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessagesAction) Reset()         { *m = GetMessagesAction{} }
func (m *GetMessagesAction) String() string { return proto.CompactTextString(m) }
func (*GetMessagesAction) ProtoMessage()    {}
func (*GetMessagesAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{7}
}

func (m *GetMessagesAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesAction.Unmarshal(m, b)
}
func (m *GetMessagesAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesAction.Marshal(b, m, deterministic)
}
func (m *GetMessagesAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesAction.Merge(m, src)
}
func (m *GetMessagesAction) XXX_Size() int {
	return xxx_messageInfo_GetMessagesAction.Size(m)
}
func (m *GetMessagesAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesAction.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesAction proto.InternalMessageInfo

func (m *GetMessagesAction) GetSession() int64 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *GetMessagesAction) GetCond() string {
	if m != nil {
		return m.Cond
	}
	return ""
}

func (m *GetMessagesAction) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetSessionsAction struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSessionsAction) Reset()         { *m = GetSessionsAction{} }
func (m *GetSessionsAction) String() string { return proto.CompactTextString(m) }
func (*GetSessionsAction) ProtoMessage()    {}
func (*GetSessionsAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{8}
}

func (m *GetSessionsAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionsAction.Unmarshal(m, b)
}
func (m *GetSessionsAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionsAction.Marshal(b, m, deterministic)
}
func (m *GetSessionsAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionsAction.Merge(m, src)
}
func (m *GetSessionsAction) XXX_Size() int {
	return xxx_messageInfo_GetSessionsAction.Size(m)
}
func (m *GetSessionsAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionsAction.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionsAction proto.InternalMessageInfo

func (m *GetSessionsAction) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type GetSessionAction struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionAction) Reset()         { *m = GetSessionAction{} }
func (m *GetSessionAction) String() string { return proto.CompactTextString(m) }
func (*GetSessionAction) ProtoMessage()    {}
func (*GetSessionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{9}
}

func (m *GetSessionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionAction.Unmarshal(m, b)
}
func (m *GetSessionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionAction.Marshal(b, m, deterministic)
}
func (m *GetSessionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionAction.Merge(m, src)
}
func (m *GetSessionAction) XXX_Size() int {
	return xxx_messageInfo_GetSessionAction.Size(m)
}
func (m *GetSessionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionAction.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionAction proto.InternalMessageInfo

func (m *GetSessionAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *GetSessionAction) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type GetMembersAction struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Members              []*User  `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMembersAction) Reset()         { *m = GetMembersAction{} }
func (m *GetMembersAction) String() string { return proto.CompactTextString(m) }
func (*GetMembersAction) ProtoMessage()    {}
func (*GetMembersAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{10}
}

func (m *GetMembersAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMembersAction.Unmarshal(m, b)
}
func (m *GetMembersAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMembersAction.Marshal(b, m, deterministic)
}
func (m *GetMembersAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMembersAction.Merge(m, src)
}
func (m *GetMembersAction) XXX_Size() int {
	return xxx_messageInfo_GetMembersAction.Size(m)
}
func (m *GetMembersAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMembersAction.DiscardUnknown(m)
}

var xxx_messageInfo_GetMembersAction proto.InternalMessageInfo

func (m *GetMembersAction) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *GetMembersAction) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.ActType", ActType_name, ActType_value)
	proto.RegisterType((*Action)(nil), "rpc.Action")
	proto.RegisterType((*CreateSessionAction)(nil), "rpc.CreateSessionAction")
	proto.RegisterType((*JoinSessionAction)(nil), "rpc.JoinSessionAction")
	proto.RegisterType((*QuitSessionAction)(nil), "rpc.QuitSessionAction")
	proto.RegisterType((*WithdrawMessageAction)(nil), "rpc.WithdrawMessageAction")
	proto.RegisterType((*SyncMessageAction)(nil), "rpc.SyncMessageAction")
	proto.RegisterType((*RenameSessionAction)(nil), "rpc.RenameSessionAction")
	proto.RegisterType((*GetMessagesAction)(nil), "rpc.GetMessagesAction")
	proto.RegisterType((*GetSessionsAction)(nil), "rpc.GetSessionsAction")
	proto.RegisterType((*GetSessionAction)(nil), "rpc.GetSessionAction")
	proto.RegisterType((*GetMembersAction)(nil), "rpc.GetMembersAction")
}

func init() { proto.RegisterFile("action.proto", fileDescriptor_59885c909ad4dfd3) }

var fileDescriptor_59885c909ad4dfd3 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x49, 0xd7, 0x36, 0xaf, 0xd5, 0x70, 0x3d, 0x81, 0xa2, 0x69, 0xa0, 0x28, 0x20, 0x14,
	0x71, 0xd8, 0x61, 0x9c, 0x39, 0x64, 0x25, 0x1a, 0x19, 0x6a, 0xc6, 0x9c, 0x56, 0x65, 0x5c, 0x50,
	0x96, 0x58, 0x23, 0x1a, 0x49, 0x4a, 0xec, 0x31, 0xed, 0xe7, 0x70, 0xe3, 0x47, 0xf0, 0xe3, 0x90,
	0x1d, 0xbb, 0x69, 0x39, 0xc0, 0x76, 0xf3, 0xf7, 0xbd, 0xf7, 0xbe, 0xef, 0x73, 0x9f, 0x1b, 0x18,
	0xa7, 0x19, 0x2f, 0xea, 0xea, 0x70, 0xd5, 0xd4, 0xbc, 0xc6, 0x56, 0xb3, 0xca, 0xf6, 0x47, 0x65,
	0x9d, 0xd3, 0x6f, 0x2d, 0xb3, 0x6f, 0x97, 0xec, 0xaa, 0x3d, 0x7a, 0xbf, 0x0c, 0xe8, 0x07, 0xb2,
	0x1b, 0x3f, 0x85, 0xfe, 0x0d, 0xa3, 0x4d, 0x94, 0x3b, 0x86, 0x6b, 0xf8, 0x16, 0x51, 0x08, 0x3f,
	0x07, 0x68, 0x68, 0x59, 0x73, 0x1a, 0xe4, 0x79, 0xe3, 0x98, 0xae, 0xe1, 0xdb, 0x64, 0x83, 0xc1,
	0x07, 0x60, 0x37, 0xf4, 0xfb, 0x0d, 0x65, 0x3c, 0xca, 0x1d, 0x4b, 0x8e, 0x76, 0x04, 0xc6, 0xd0,
	0xe3, 0x45, 0x49, 0x9d, 0x9e, 0x2c, 0xc8, 0x33, 0x76, 0xa1, 0xc7, 0xef, 0x56, 0xd4, 0xd9, 0x71,
	0x0d, 0x7f, 0xf7, 0x68, 0x7c, 0xd8, 0xac, 0xb2, 0xc3, 0x20, 0xe3, 0xf3, 0xbb, 0x15, 0x25, 0xb2,
	0x22, 0xa6, 0xf2, 0x94, 0xa7, 0x4e, 0xdf, 0x35, 0xfc, 0x31, 0x91, 0x67, 0xef, 0xa7, 0x01, 0x7b,
	0xd3, 0x86, 0xa6, 0x9c, 0x26, 0x94, 0xb1, 0xa2, 0xae, 0x54, 0xee, 0x03, 0xb0, 0x59, 0x4b, 0xac,
	0xa3, 0x77, 0x04, 0x76, 0x60, 0x50, 0xdf, 0x56, 0xf2, 0x5a, 0xa6, 0xac, 0x69, 0x28, 0x3c, 0xaa,
	0xb4, 0xa4, 0x32, 0xb2, 0x4d, 0xe4, 0x59, 0x74, 0xb7, 0xb7, 0x66, 0x4e, 0xcf, 0xb5, 0x44, 0xb7,
	0x82, 0xf8, 0xe5, 0x56, 0x66, 0x24, 0x33, 0xab, 0x1c, 0x5d, 0x6e, 0xef, 0x23, 0x4c, 0x4e, 0xeb,
	0xa2, 0x7a, 0x48, 0xc0, 0x67, 0xd0, 0x13, 0x1e, 0x32, 0xdd, 0xe8, 0xc8, 0x96, 0xc2, 0x0b, 0x46,
	0x1b, 0x22, 0x69, 0x2f, 0x82, 0xc9, 0xf9, 0x4d, 0xc1, 0x1f, 0xa2, 0xd8, 0x2d, 0xd2, 0xdc, 0x5c,
	0xa4, 0x77, 0x0d, 0x4f, 0x96, 0x05, 0xff, 0x9a, 0x37, 0xe9, 0xed, 0x8c, 0x32, 0x96, 0x5e, 0xd1,
	0xff, 0x6c, 0x7e, 0xcb, 0xc6, 0xfc, 0xdb, 0xe6, 0x00, 0xec, 0xb2, 0x95, 0xe9, 0xf6, 0xbe, 0x26,
	0xbc, 0x0b, 0x98, 0x24, 0x77, 0x55, 0xb6, 0x6d, 0xb4, 0x0f, 0xc3, 0x9c, 0xfe, 0x28, 0x32, 0xba,
	0xb6, 0x5a, 0x63, 0xec, 0xc3, 0x50, 0x4d, 0x33, 0xc7, 0x74, 0x2d, 0x7f, 0xa4, 0x1e, 0x86, 0x52,
	0x20, 0xeb, 0xaa, 0x77, 0x02, 0x7b, 0x84, 0x8a, 0x75, 0x3d, 0xe4, 0x47, 0xd1, 0xdb, 0x36, 0xbb,
	0x6d, 0x7b, 0xd7, 0x30, 0x39, 0xa1, 0x5c, 0x19, 0x30, 0x25, 0xe3, 0xc0, 0x40, 0x4d, 0x29, 0x11,
	0x0d, 0x85, 0x44, 0x56, 0x57, 0xb9, 0x96, 0x10, 0xe7, 0xad, 0xd4, 0xd6, 0x3f, 0x53, 0xbf, 0x95,
	0x66, 0x2a, 0xb2, 0x36, 0xf3, 0x61, 0xa8, 0xd4, 0x99, 0x63, 0x6c, 0x8c, 0xab, 0x36, 0xb2, 0xae,
	0x7a, 0x9f, 0x00, 0x75, 0xe3, 0xf7, 0xba, 0xf1, 0xab, 0xee, 0x22, 0xed, 0xdb, 0xda, 0x96, 0xd6,
	0x45, 0x6f, 0x21, 0x95, 0x67, 0xb4, 0xbc, 0xa4, 0x0d, 0xbb, 0x97, 0xf2, 0x0b, 0x18, 0x94, 0x6d,
	0xbb, 0xda, 0xd4, 0xc6, 0xab, 0xd5, 0x95, 0xd7, 0xbf, 0x0d, 0x18, 0xa8, 0x3f, 0x35, 0x7e, 0x0c,
	0xa3, 0x60, 0x3a, 0xff, 0xb2, 0x88, 0x3f, 0xc4, 0x67, 0xcb, 0x18, 0x3d, 0xc2, 0x63, 0x18, 0x0a,
	0xe2, 0xf4, 0x2c, 0x8a, 0x91, 0xa1, 0xd1, 0xf9, 0x22, 0x9a, 0x23, 0x13, 0x23, 0x18, 0x0b, 0xb4,
	0x8c, 0xe6, 0xef, 0xdf, 0x91, 0x60, 0x89, 0x2c, 0x5d, 0x4f, 0x2e, 0xe2, 0x29, 0xea, 0xe1, 0x5d,
	0x00, 0x81, 0x48, 0x18, 0x07, 0xb3, 0x10, 0xed, 0x68, 0x3c, 0x25, 0x61, 0x30, 0x0f, 0x51, 0x5f,
	0x9b, 0x25, 0x61, 0x92, 0x44, 0x67, 0x31, 0x1a, 0x68, 0x41, 0x45, 0x24, 0x68, 0xa8, 0x5b, 0x66,
	0xe1, 0xec, 0x38, 0x24, 0x09, 0xb2, 0x75, 0xcb, 0x2c, 0x4c, 0x92, 0xe0, 0x24, 0x4c, 0x10, 0x1c,
	0xef, 0x7c, 0x16, 0xdf, 0xcd, 0xcb, 0xbe, 0xfc, 0x4c, 0xbe, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0x96, 0x55, 0xf8, 0x53, 0x05, 0x00, 0x00,
}
