// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionType int32

const (
	SessionType_SESSION_UNKNOWN SessionType = 0
	SessionType_SESSION_PERSON  SessionType = 1
	SessionType_SESSION_GROUP   SessionType = 2
)

var SessionType_name = map[int32]string{
	0: "SESSION_UNKNOWN",
	1: "SESSION_PERSON",
	2: "SESSION_GROUP",
}

var SessionType_value = map[string]int32{
	"SESSION_UNKNOWN": 0,
	"SESSION_PERSON":  1,
	"SESSION_GROUP":   2,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type RegisterReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Server               string   `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	SerialNo             string   `protobuf:"bytes,5,opt,name=serialNo,proto3" json:"serialNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegisterReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *RegisterReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *RegisterReq) GetSerialNo() string {
	if m != nil {
		return m.SerialNo
	}
	return ""
}

type RegisterResp struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	LastSequence         int64    `protobuf:"varint,3,opt,name=lastSequence,proto3" json:"lastSequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *RegisterResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *RegisterResp) GetLastSequence() int64 {
	if m != nil {
		return m.LastSequence
	}
	return 0
}

type Session struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 SessionType `protobuf:"varint,3,opt,name=type,proto3,enum=rpc.SessionType" json:"type,omitempty"`
	Owner                int64       `protobuf:"varint,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Session) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Session) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_SESSION_UNKNOWN
}

func (m *Session) GetOwner() int64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

type CreateSessionReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Creater              int64    `protobuf:"varint,2,opt,name=creater,proto3" json:"creater,omitempty"`
	UserIds              []int64  `protobuf:"varint,3,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionReq) Reset()         { *m = CreateSessionReq{} }
func (m *CreateSessionReq) String() string { return proto.CompactTextString(m) }
func (*CreateSessionReq) ProtoMessage()    {}
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *CreateSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionReq.Unmarshal(m, b)
}
func (m *CreateSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionReq.Marshal(b, m, deterministic)
}
func (m *CreateSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionReq.Merge(m, src)
}
func (m *CreateSessionReq) XXX_Size() int {
	return xxx_messageInfo_CreateSessionReq.Size(m)
}
func (m *CreateSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionReq proto.InternalMessageInfo

func (m *CreateSessionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSessionReq) GetCreater() int64 {
	if m != nil {
		return m.Creater
	}
	return 0
}

func (m *CreateSessionReq) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type JoinSessionReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSessionReq) Reset()         { *m = JoinSessionReq{} }
func (m *JoinSessionReq) String() string { return proto.CompactTextString(m) }
func (*JoinSessionReq) ProtoMessage()    {}
func (*JoinSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *JoinSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSessionReq.Unmarshal(m, b)
}
func (m *JoinSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSessionReq.Marshal(b, m, deterministic)
}
func (m *JoinSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSessionReq.Merge(m, src)
}
func (m *JoinSessionReq) XXX_Size() int {
	return xxx_messageInfo_JoinSessionReq.Size(m)
}
func (m *JoinSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSessionReq proto.InternalMessageInfo

func (m *JoinSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type QuitSessionReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitSessionReq) Reset()         { *m = QuitSessionReq{} }
func (m *QuitSessionReq) String() string { return proto.CompactTextString(m) }
func (*QuitSessionReq) ProtoMessage()    {}
func (*QuitSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *QuitSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitSessionReq.Unmarshal(m, b)
}
func (m *QuitSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitSessionReq.Marshal(b, m, deterministic)
}
func (m *QuitSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitSessionReq.Merge(m, src)
}
func (m *QuitSessionReq) XXX_Size() int {
	return xxx_messageInfo_QuitSessionReq.Size(m)
}
func (m *QuitSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitSessionReq proto.InternalMessageInfo

func (m *QuitSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QuitSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WithdrawMessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageId            int64    `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawMessageReq) Reset()         { *m = WithdrawMessageReq{} }
func (m *WithdrawMessageReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawMessageReq) ProtoMessage()    {}
func (*WithdrawMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *WithdrawMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawMessageReq.Unmarshal(m, b)
}
func (m *WithdrawMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawMessageReq.Marshal(b, m, deterministic)
}
func (m *WithdrawMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawMessageReq.Merge(m, src)
}
func (m *WithdrawMessageReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawMessageReq.Size(m)
}
func (m *WithdrawMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawMessageReq proto.InternalMessageInfo

func (m *WithdrawMessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WithdrawMessageReq) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type RenameSessionReq struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameSessionReq) Reset()         { *m = RenameSessionReq{} }
func (m *RenameSessionReq) String() string { return proto.CompactTextString(m) }
func (*RenameSessionReq) ProtoMessage()    {}
func (*RenameSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *RenameSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameSessionReq.Unmarshal(m, b)
}
func (m *RenameSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameSessionReq.Marshal(b, m, deterministic)
}
func (m *RenameSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameSessionReq.Merge(m, src)
}
func (m *RenameSessionReq) XXX_Size() int {
	return xxx_messageInfo_RenameSessionReq.Size(m)
}
func (m *RenameSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_RenameSessionReq proto.InternalMessageInfo

func (m *RenameSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RenameSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RenameSessionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//1. 不传seq时按服务端自己保存的最后序列号往后查询
//2. seq为int64  获取单条
//3. seq有，用in获取
//4. seq有>，按范围获取
type SyncMessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SeqRanges            []string `protobuf:"bytes,2,rep,name=seqRanges,proto3" json:"seqRanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageReq) Reset()         { *m = SyncMessageReq{} }
func (m *SyncMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageReq) ProtoMessage()    {}
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}

func (m *SyncMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageReq.Unmarshal(m, b)
}
func (m *SyncMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageReq.Merge(m, src)
}
func (m *SyncMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageReq.Size(m)
}
func (m *SyncMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageReq proto.InternalMessageInfo

func (m *SyncMessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SyncMessageReq) GetSeqRanges() []string {
	if m != nil {
		return m.SeqRanges
	}
	return nil
}

type OfflineReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	LastSequence         int64    `protobuf:"varint,3,opt,name=lastSequence,proto3" json:"lastSequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineReq) Reset()         { *m = OfflineReq{} }
func (m *OfflineReq) String() string { return proto.CompactTextString(m) }
func (*OfflineReq) ProtoMessage()    {}
func (*OfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{10}
}

func (m *OfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineReq.Unmarshal(m, b)
}
func (m *OfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineReq.Marshal(b, m, deterministic)
}
func (m *OfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineReq.Merge(m, src)
}
func (m *OfflineReq) XXX_Size() int {
	return xxx_messageInfo_OfflineReq.Size(m)
}
func (m *OfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineReq proto.InternalMessageInfo

func (m *OfflineReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OfflineReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *OfflineReq) GetLastSequence() int64 {
	if m != nil {
		return m.LastSequence
	}
	return 0
}

func init() {
	proto.RegisterEnum("rpc.SessionType", SessionType_name, SessionType_value)
	proto.RegisterType((*RegisterReq)(nil), "rpc.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "rpc.RegisterResp")
	proto.RegisterType((*Session)(nil), "rpc.Session")
	proto.RegisterType((*CreateSessionReq)(nil), "rpc.CreateSessionReq")
	proto.RegisterType((*JoinSessionReq)(nil), "rpc.JoinSessionReq")
	proto.RegisterType((*QuitSessionReq)(nil), "rpc.QuitSessionReq")
	proto.RegisterType((*User)(nil), "rpc.User")
	proto.RegisterType((*WithdrawMessageReq)(nil), "rpc.WithdrawMessageReq")
	proto.RegisterType((*RenameSessionReq)(nil), "rpc.RenameSessionReq")
	proto.RegisterType((*SyncMessageReq)(nil), "rpc.SyncMessageReq")
	proto.RegisterType((*OfflineReq)(nil), "rpc.OfflineReq")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0x71, 0xbb, 0xad, 0xb7, 0x23, 0x04, 0x83, 0x50, 0x84, 0x78, 0xa8, 0x22, 0x1e, 0xaa,
	0x3d, 0xf4, 0x01, 0xfe, 0x00, 0xb4, 0xa1, 0x0e, 0x91, 0x0c, 0x87, 0x6a, 0xd2, 0x84, 0x04, 0x21,
	0xbe, 0x2b, 0x16, 0xad, 0x93, 0xda, 0xee, 0xa6, 0x3e, 0xf3, 0xe3, 0xc8, 0x4e, 0xd2, 0xa6, 0x48,
	0xb0, 0x49, 0x7b, 0xf3, 0x39, 0xd7, 0xf7, 0xdc, 0x73, 0x6e, 0x22, 0xc3, 0x70, 0x59, 0x72, 0x5c,
	0x4c, 0x2a, 0x55, 0x9a, 0x92, 0x12, 0x55, 0x15, 0xf1, 0x6f, 0x0f, 0x86, 0x0c, 0xe7, 0x42, 0x1b,
	0x54, 0x0c, 0x57, 0xf4, 0x05, 0x1c, 0xac, 0x35, 0xaa, 0x29, 0x8f, 0xbc, 0x91, 0x37, 0x26, 0xac,
	0x41, 0xf4, 0x39, 0xf4, 0x4d, 0xf9, 0x0b, 0x65, 0xe4, 0x8f, 0xbc, 0xf1, 0x80, 0xd5, 0x80, 0x52,
	0xe8, 0xe5, 0x9c, 0xab, 0x88, 0x38, 0xd2, 0x9d, 0xad, 0x82, 0x46, 0x75, 0x83, 0x2a, 0xea, 0x39,
	0xb6, 0x41, 0xf4, 0x25, 0x1c, 0x69, 0x54, 0x22, 0x5f, 0x24, 0x65, 0xd4, 0x77, 0x95, 0x2d, 0x8e,
	0xbf, 0xc3, 0xf1, 0xce, 0x84, 0xae, 0x68, 0x08, 0x44, 0xa1, 0x71, 0x16, 0x8e, 0x98, 0x3d, 0xda,
	0x6e, 0x8e, 0x37, 0xa2, 0xc0, 0x29, 0x77, 0x16, 0x08, 0xdb, 0x62, 0x1a, 0xc3, 0xf1, 0x22, 0xd7,
	0x26, 0xc3, 0xd5, 0x1a, 0x65, 0x81, 0xce, 0x0d, 0x61, 0x7b, 0x5c, 0x2c, 0xe0, 0x30, 0x43, 0xad,
	0x45, 0x29, 0x69, 0x00, 0xbe, 0x68, 0xe3, 0xf9, 0x82, 0xdb, 0x10, 0x32, 0x5f, 0x62, 0x93, 0xcc,
	0x9d, 0xe9, 0x6b, 0xe8, 0x99, 0x4d, 0x55, 0x4b, 0x05, 0x6f, 0xc2, 0x89, 0xaa, 0x8a, 0x49, 0xd3,
	0xff, 0x65, 0x53, 0x21, 0x73, 0x55, 0xbb, 0x94, 0xf2, 0x56, 0x36, 0x49, 0x09, 0xab, 0x41, 0x7c,
	0x05, 0xe1, 0x7b, 0x85, 0xb9, 0xc1, 0xa6, 0xc1, 0xae, 0xb5, 0x9d, 0xe1, 0x75, 0x66, 0x44, 0x70,
	0x58, 0xb8, 0x7b, 0xaa, 0x49, 0xd4, 0x42, 0x5b, 0xa9, 0xd7, 0xae, 0x23, 0x32, 0x22, 0xb6, 0xd2,
	0xc0, 0xf8, 0x0c, 0x82, 0xf3, 0x52, 0xc8, 0x8e, 0xf2, 0xbf, 0x3e, 0xd8, 0x2b, 0x18, 0xe8, 0xfa,
	0xd6, 0x76, 0x63, 0x3b, 0xc2, 0xea, 0x7c, 0x5e, 0x0b, 0xf3, 0x60, 0x9d, 0x13, 0xe8, 0xcd, 0x34,
	0xaa, 0xfb, 0xec, 0x34, 0x3e, 0x07, 0x7a, 0x29, 0xcc, 0x4f, 0xae, 0xf2, 0xdb, 0x4f, 0xa8, 0x75,
	0x3e, 0xc7, 0x3b, 0xe6, 0x2e, 0xeb, 0x5b, 0xbb, 0xb9, 0x5b, 0x22, 0xfe, 0x0a, 0x21, 0x43, 0xab,
	0xda, 0x49, 0xb0, 0xe7, 0xd4, 0xfb, 0xcb, 0x69, 0x67, 0x8e, 0xbf, 0x37, 0xa7, 0x75, 0x4a, 0x3a,
	0x4e, 0xcf, 0x20, 0xc8, 0x36, 0xb2, 0xb8, 0x9f, 0x4b, 0x8d, 0x2b, 0x96, 0xcb, 0x39, 0xea, 0xc8,
	0x1f, 0x91, 0xf1, 0x80, 0xed, 0x88, 0x98, 0x03, 0xa4, 0xd7, 0xd7, 0x0b, 0x21, 0xff, 0xab, 0xf1,
	0xc0, 0x5f, 0xfb, 0x64, 0x0a, 0xc3, 0xce, 0xaf, 0x49, 0x9f, 0xc1, 0x93, 0xec, 0x34, 0xcb, 0xa6,
	0x69, 0xf2, 0x6d, 0x96, 0x7c, 0x4c, 0xd2, 0xcb, 0x24, 0x7c, 0x44, 0x29, 0x04, 0x2d, 0x79, 0x71,
	0xca, 0xb2, 0x34, 0x09, 0x3d, 0xfa, 0x14, 0x1e, 0xb7, 0xdc, 0x07, 0x96, 0xce, 0x2e, 0x42, 0xff,
	0x5d, 0xff, 0xca, 0x3e, 0x0a, 0x3f, 0x0e, 0xdc, 0x03, 0xf1, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x41, 0x23, 0x72, 0x2f, 0x04, 0x00, 0x00,
}
