// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionType int32

const (
	SessionType_SESSION_UNKNOWN SessionType = 0
	SessionType_SESSION_PERSON  SessionType = 1
	SessionType_SESSION_GROUP   SessionType = 2
)

var SessionType_name = map[int32]string{
	0: "SESSION_UNKNOWN",
	1: "SESSION_PERSON",
	2: "SESSION_GROUP",
}

var SessionType_value = map[string]int32{
	"SESSION_UNKNOWN": 0,
	"SESSION_PERSON":  1,
	"SESSION_GROUP":   2,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type AuthReq struct {
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthResp struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *AuthResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidReq) Reset()         { *m = ValidReq{} }
func (m *ValidReq) String() string { return proto.CompactTextString(m) }
func (*ValidReq) ProtoMessage()    {}
func (*ValidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *ValidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidReq.Unmarshal(m, b)
}
func (m *ValidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidReq.Marshal(b, m, deterministic)
}
func (m *ValidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidReq.Merge(m, src)
}
func (m *ValidReq) XXX_Size() int {
	return xxx_messageInfo_ValidReq.Size(m)
}
func (m *ValidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidReq proto.InternalMessageInfo

func (m *ValidReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ValidReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *ValidReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidResp struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidResp) Reset()         { *m = ValidResp{} }
func (m *ValidResp) String() string { return proto.CompactTextString(m) }
func (*ValidResp) ProtoMessage()    {}
func (*ValidResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *ValidResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidResp.Unmarshal(m, b)
}
func (m *ValidResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidResp.Marshal(b, m, deterministic)
}
func (m *ValidResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidResp.Merge(m, src)
}
func (m *ValidResp) XXX_Size() int {
	return xxx_messageInfo_ValidResp.Size(m)
}
func (m *ValidResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidResp proto.InternalMessageInfo

func (m *ValidResp) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

type RegInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	SerialNo             string   `protobuf:"bytes,3,opt,name=serialNo,proto3" json:"serialNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegInfo) Reset()         { *m = RegInfo{} }
func (m *RegInfo) String() string { return proto.CompactTextString(m) }
func (*RegInfo) ProtoMessage()    {}
func (*RegInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *RegInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegInfo.Unmarshal(m, b)
}
func (m *RegInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegInfo.Marshal(b, m, deterministic)
}
func (m *RegInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegInfo.Merge(m, src)
}
func (m *RegInfo) XXX_Size() int {
	return xxx_messageInfo_RegInfo.Size(m)
}
func (m *RegInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegInfo proto.InternalMessageInfo

func (m *RegInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegInfo) GetSerialNo() string {
	if m != nil {
		return m.SerialNo
	}
	return ""
}

type RegisterReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Server               string   `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	SerialNo             string   `protobuf:"bytes,5,opt,name=serialNo,proto3" json:"serialNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegisterReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *RegisterReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *RegisterReq) GetSerialNo() string {
	if m != nil {
		return m.SerialNo
	}
	return ""
}

type RegisterResp struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type Session struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 SessionType `protobuf:"varint,3,opt,name=type,proto3,enum=rpc.SessionType" json:"type,omitempty"`
	Owner                int64       `protobuf:"varint,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Session) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Session) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_SESSION_UNKNOWN
}

func (m *Session) GetOwner() int64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

type CreateSessionReq struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Creater              int64       `protobuf:"varint,2,opt,name=creater,proto3" json:"creater,omitempty"`
	UserIds              []int64     `protobuf:"varint,3,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	Type                 SessionType `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.SessionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSessionReq) Reset()         { *m = CreateSessionReq{} }
func (m *CreateSessionReq) String() string { return proto.CompactTextString(m) }
func (*CreateSessionReq) ProtoMessage()    {}
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *CreateSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionReq.Unmarshal(m, b)
}
func (m *CreateSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionReq.Marshal(b, m, deterministic)
}
func (m *CreateSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionReq.Merge(m, src)
}
func (m *CreateSessionReq) XXX_Size() int {
	return xxx_messageInfo_CreateSessionReq.Size(m)
}
func (m *CreateSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionReq proto.InternalMessageInfo

func (m *CreateSessionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSessionReq) GetCreater() int64 {
	if m != nil {
		return m.Creater
	}
	return 0
}

func (m *CreateSessionReq) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *CreateSessionReq) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_SESSION_UNKNOWN
}

type SessionResp struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Members              []*User  `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionResp) Reset()         { *m = SessionResp{} }
func (m *SessionResp) String() string { return proto.CompactTextString(m) }
func (*SessionResp) ProtoMessage()    {}
func (*SessionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}

func (m *SessionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResp.Unmarshal(m, b)
}
func (m *SessionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResp.Marshal(b, m, deterministic)
}
func (m *SessionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResp.Merge(m, src)
}
func (m *SessionResp) XXX_Size() int {
	return xxx_messageInfo_SessionResp.Size(m)
}
func (m *SessionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResp.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResp proto.InternalMessageInfo

func (m *SessionResp) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SessionResp) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

type JoinSessionReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSessionReq) Reset()         { *m = JoinSessionReq{} }
func (m *JoinSessionReq) String() string { return proto.CompactTextString(m) }
func (*JoinSessionReq) ProtoMessage()    {}
func (*JoinSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{10}
}

func (m *JoinSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSessionReq.Unmarshal(m, b)
}
func (m *JoinSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSessionReq.Marshal(b, m, deterministic)
}
func (m *JoinSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSessionReq.Merge(m, src)
}
func (m *JoinSessionReq) XXX_Size() int {
	return xxx_messageInfo_JoinSessionReq.Size(m)
}
func (m *JoinSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSessionReq proto.InternalMessageInfo

func (m *JoinSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type QuitSessionReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitSessionReq) Reset()         { *m = QuitSessionReq{} }
func (m *QuitSessionReq) String() string { return proto.CompactTextString(m) }
func (*QuitSessionReq) ProtoMessage()    {}
func (*QuitSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{11}
}

func (m *QuitSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitSessionReq.Unmarshal(m, b)
}
func (m *QuitSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitSessionReq.Marshal(b, m, deterministic)
}
func (m *QuitSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitSessionReq.Merge(m, src)
}
func (m *QuitSessionReq) XXX_Size() int {
	return xxx_messageInfo_QuitSessionReq.Size(m)
}
func (m *QuitSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitSessionReq proto.InternalMessageInfo

func (m *QuitSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QuitSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type WithdrawMessageReq struct {
	SenderId             int64    `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	MessageId            int64    `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	SessionId            int64    `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawMessageReq) Reset()         { *m = WithdrawMessageReq{} }
func (m *WithdrawMessageReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawMessageReq) ProtoMessage()    {}
func (*WithdrawMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{13}
}

func (m *WithdrawMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawMessageReq.Unmarshal(m, b)
}
func (m *WithdrawMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawMessageReq.Marshal(b, m, deterministic)
}
func (m *WithdrawMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawMessageReq.Merge(m, src)
}
func (m *WithdrawMessageReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawMessageReq.Size(m)
}
func (m *WithdrawMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawMessageReq proto.InternalMessageInfo

func (m *WithdrawMessageReq) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *WithdrawMessageReq) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *WithdrawMessageReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type RenameSessionReq struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameSessionReq) Reset()         { *m = RenameSessionReq{} }
func (m *RenameSessionReq) String() string { return proto.CompactTextString(m) }
func (*RenameSessionReq) ProtoMessage()    {}
func (*RenameSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{14}
}

func (m *RenameSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameSessionReq.Unmarshal(m, b)
}
func (m *RenameSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameSessionReq.Marshal(b, m, deterministic)
}
func (m *RenameSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameSessionReq.Merge(m, src)
}
func (m *RenameSessionReq) XXX_Size() int {
	return xxx_messageInfo_RenameSessionReq.Size(m)
}
func (m *RenameSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_RenameSessionReq proto.InternalMessageInfo

func (m *RenameSessionReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RenameSessionReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RenameSessionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//1. 不传seq时按服务端自己保存的最后序列号往后查询
//2. seq为int64  获取单条
//3. seq有,用in获取
//4. seq有>按范围获取
type GetMessageReq struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Condition            string   `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageReq) Reset()         { *m = GetMessageReq{} }
func (m *GetMessageReq) String() string { return proto.CompactTextString(m) }
func (*GetMessageReq) ProtoMessage()    {}
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{15}
}

func (m *GetMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageReq.Unmarshal(m, b)
}
func (m *GetMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageReq.Marshal(b, m, deterministic)
}
func (m *GetMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageReq.Merge(m, src)
}
func (m *GetMessageReq) XXX_Size() int {
	return xxx_messageInfo_GetMessageReq.Size(m)
}
func (m *GetMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageReq proto.InternalMessageInfo

func (m *GetMessageReq) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *GetMessageReq) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type SyncMessageReq struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageReq) Reset()         { *m = SyncMessageReq{} }
func (m *SyncMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageReq) ProtoMessage()    {}
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{16}
}

func (m *SyncMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageReq.Unmarshal(m, b)
}
func (m *SyncMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageReq.Merge(m, src)
}
func (m *SyncMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageReq.Size(m)
}
func (m *SyncMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageReq proto.InternalMessageInfo

func (m *SyncMessageReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type OfflineReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineReq) Reset()         { *m = OfflineReq{} }
func (m *OfflineReq) String() string { return proto.CompactTextString(m) }
func (*OfflineReq) ProtoMessage()    {}
func (*OfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{17}
}

func (m *OfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineReq.Unmarshal(m, b)
}
func (m *OfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineReq.Marshal(b, m, deterministic)
}
func (m *OfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineReq.Merge(m, src)
}
func (m *OfflineReq) XXX_Size() int {
	return xxx_messageInfo_OfflineReq.Size(m)
}
func (m *OfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineReq proto.InternalMessageInfo

func (m *OfflineReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OfflineReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterEnum("rpc.SessionType", SessionType_name, SessionType_value)
	proto.RegisterType((*AuthReq)(nil), "rpc.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "rpc.AuthResp")
	proto.RegisterType((*ValidReq)(nil), "rpc.ValidReq")
	proto.RegisterType((*ValidResp)(nil), "rpc.ValidResp")
	proto.RegisterType((*RegInfo)(nil), "rpc.RegInfo")
	proto.RegisterType((*RegisterReq)(nil), "rpc.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "rpc.RegisterResp")
	proto.RegisterType((*Session)(nil), "rpc.Session")
	proto.RegisterType((*CreateSessionReq)(nil), "rpc.CreateSessionReq")
	proto.RegisterType((*SessionResp)(nil), "rpc.SessionResp")
	proto.RegisterType((*JoinSessionReq)(nil), "rpc.JoinSessionReq")
	proto.RegisterType((*QuitSessionReq)(nil), "rpc.QuitSessionReq")
	proto.RegisterType((*User)(nil), "rpc.User")
	proto.RegisterType((*WithdrawMessageReq)(nil), "rpc.WithdrawMessageReq")
	proto.RegisterType((*RenameSessionReq)(nil), "rpc.RenameSessionReq")
	proto.RegisterType((*GetMessageReq)(nil), "rpc.GetMessageReq")
	proto.RegisterType((*SyncMessageReq)(nil), "rpc.SyncMessageReq")
	proto.RegisterType((*OfflineReq)(nil), "rpc.OfflineReq")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0xdd, 0xad, 0xed, 0x75, 0x2b, 0xc1, 0x20, 0x14, 0xa1, 0x4d, 0xaa, 0x02, 0x42,
	0xd3, 0x84, 0xf6, 0x30, 0xbe, 0xc0, 0x00, 0x8d, 0xa9, 0x9b, 0x48, 0x87, 0xc3, 0x98, 0x34, 0x21,
	0xa1, 0x2c, 0xbe, 0x6d, 0x16, 0x6d, 0x12, 0xec, 0x74, 0xd3, 0xde, 0x90, 0xf8, 0xe2, 0xc8, 0x8e,
	0x93, 0x26, 0x53, 0x5b, 0x81, 0x78, 0xf3, 0xdd, 0xe5, 0xfe, 0xf7, 0xbb, 0xf3, 0xc5, 0xd0, 0x9f,
	0xa6, 0x1c, 0x27, 0x7b, 0x99, 0x4c, 0xf3, 0x94, 0x12, 0x99, 0xc5, 0xfe, 0x36, 0x74, 0xde, 0xcd,
	0xf2, 0x1b, 0x86, 0x3f, 0x29, 0x85, 0x76, 0x9c, 0x72, 0xf4, 0x5a, 0x43, 0x67, 0xa7, 0xc7, 0xcc,
	0xd9, 0x3f, 0x86, 0x6e, 0x11, 0x56, 0x19, 0x75, 0x81, 0x48, 0xcc, 0x3d, 0x67, 0xe8, 0xec, 0x74,
	0x99, 0x3e, 0xd2, 0xe7, 0xb0, 0x3e, 0x53, 0x28, 0x47, 0xdc, 0xe4, 0x10, 0x66, 0x2d, 0xfa, 0x0c,
	0xd6, 0xf2, 0xf4, 0x07, 0x26, 0x1e, 0x31, 0x52, 0x85, 0xe1, 0x07, 0xd0, 0xfd, 0x1a, 0x4d, 0x04,
	0xd7, 0xb5, 0x5c, 0x20, 0x33, 0xc1, 0x8d, 0x16, 0x61, 0xfa, 0x48, 0x5f, 0x40, 0x97, 0xe3, 0xad,
	0x88, 0xb1, 0x52, 0xab, 0xec, 0x25, 0x7a, 0xdb, 0xd0, 0xb3, 0x7a, 0x8b, 0xe0, 0xfc, 0x10, 0x3a,
	0x0c, 0xaf, 0x47, 0xc9, 0x55, 0x5a, 0xe3, 0x74, 0x16, 0x73, 0xb6, 0x6a, 0xba, 0x9a, 0x44, 0xa1,
	0x14, 0xd1, 0x24, 0x48, 0x6d, 0xc1, 0xca, 0xf6, 0x7f, 0x3b, 0xd0, 0x67, 0x78, 0x2d, 0x54, 0x8e,
	0x52, 0xf7, 0xf1, 0x6f, 0xca, 0x14, 0xda, 0x11, 0xe7, 0xd2, 0xaa, 0x9a, 0xb3, 0x56, 0x50, 0x28,
	0x6f, 0x51, 0x7a, 0x6d, 0xe3, 0xb5, 0x56, 0x83, 0x62, 0xed, 0x01, 0xc5, 0x2e, 0x6c, 0xcc, 0x21,
	0x54, 0xd6, 0x98, 0x9d, 0xd3, 0x9c, 0x9d, 0x2f, 0xa0, 0x13, 0xa2, 0x52, 0x22, 0x4d, 0xe8, 0x00,
	0x5a, 0xd5, 0xcc, 0x5b, 0x82, 0x6b, 0x9c, 0x24, 0x9a, 0x56, 0x17, 0xae, 0xcf, 0xf4, 0x15, 0xb4,
	0xf3, 0xfb, 0x0c, 0x0d, 0xe2, 0x60, 0xdf, 0xdd, 0x93, 0x59, 0xbc, 0x67, 0xf3, 0xbf, 0xdc, 0x67,
	0xc8, 0x4c, 0x54, 0xb7, 0x97, 0xde, 0x25, 0x96, 0x99, 0xb0, 0xc2, 0xf0, 0x7f, 0x39, 0xe0, 0x7e,
	0x90, 0x18, 0xe5, 0x68, 0x33, 0xec, 0x56, 0x99, 0x22, 0x4e, 0xad, 0x88, 0x07, 0x9d, 0xd8, 0x7c,
	0x27, 0xed, 0x55, 0x97, 0xa6, 0x8e, 0x14, 0x13, 0x54, 0x1e, 0x19, 0x12, 0x1d, 0xb1, 0x66, 0x05,
	0xd6, 0x5e, 0x05, 0xe6, 0x5f, 0x40, 0xbf, 0xaa, 0xad, 0x32, 0xfa, 0x1a, 0x3a, 0xaa, 0x30, 0x4d,
	0xfd, 0xfe, 0xfe, 0x46, 0x3d, 0x8f, 0x95, 0x41, 0xfa, 0x12, 0x3a, 0x53, 0x9c, 0x5e, 0xa2, 0x54,
	0x5e, 0x6b, 0x48, 0x76, 0xfa, 0xfb, 0x3d, 0xf3, 0xdd, 0x99, 0x42, 0xc9, 0xca, 0x88, 0xff, 0x11,
	0x06, 0xc7, 0xa9, 0x48, 0x6a, 0xbd, 0x2d, 0xbb, 0xfd, 0x2d, 0xe8, 0x59, 0xe5, 0x6a, 0x99, 0xe7,
	0x0e, 0xad, 0xf3, 0x79, 0x26, 0xf2, 0xff, 0xd6, 0x39, 0x80, 0xb6, 0x06, 0xfc, 0xab, 0x6b, 0x5d,
	0xfc, 0x07, 0x4d, 0x80, 0x9e, 0x8b, 0xfc, 0x86, 0xcb, 0xe8, 0xee, 0x13, 0x2a, 0x15, 0x5d, 0xa3,
	0xa6, 0x31, 0x9b, 0x97, 0xf0, 0x1a, 0x4f, 0x65, 0x6b, 0xa2, 0x69, 0xf1, 0xe5, 0x9c, 0xa8, 0x72,
	0x34, 0x79, 0xc9, 0x43, 0xde, 0x6f, 0xe0, 0x32, 0xd4, 0x34, 0xb5, 0xce, 0x1b, 0x19, 0xce, 0x83,
	0x8c, 0xa5, 0xef, 0x4b, 0xd9, 0x21, 0x99, 0x77, 0xe8, 0x9f, 0xc0, 0xe6, 0x11, 0xe6, 0xb5, 0x36,
	0x56, 0x4b, 0x6f, 0x41, 0x2f, 0x4e, 0x13, 0x2e, 0x72, 0xbd, 0x1b, 0xc5, 0xa4, 0xe6, 0x0e, 0xff,
	0x0d, 0x0c, 0xc2, 0xfb, 0x24, 0x6e, 0x0e, 0x65, 0xe9, 0x2f, 0x76, 0x00, 0x30, 0xbe, 0xba, 0x9a,
	0x88, 0x04, 0x57, 0x5d, 0xe6, 0x8a, 0x07, 0x6e, 0x77, 0x54, 0xad, 0xad, 0xde, 0x65, 0xfa, 0x14,
	0x1e, 0x87, 0x87, 0x61, 0x38, 0x1a, 0x07, 0xdf, 0xcf, 0x82, 0x93, 0x60, 0x7c, 0x1e, 0xb8, 0x8f,
	0x28, 0x85, 0x41, 0xe9, 0x3c, 0x3d, 0x64, 0xe1, 0x38, 0x70, 0x1d, 0xfa, 0x04, 0x36, 0x4b, 0xdf,
	0x11, 0x1b, 0x9f, 0x9d, 0xba, 0xad, 0xf7, 0x6b, 0x17, 0xfa, 0x5d, 0xbf, 0x5c, 0x37, 0x6f, 0xfc,
	0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x43, 0xdd, 0x4f, 0xf2, 0x05, 0x00, 0x00,
}
