// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_MT_UNKNOWN MsgType = 0
	MsgType_MT_TEXT    MsgType = 1
	MsgType_MT_EMOJI   MsgType = 2
	MsgType_MT_VOICE   MsgType = 3
	MsgType_MT_IMAGE   MsgType = 4
	MsgType_MT_FILE    MsgType = 5
	MsgType_MT_GEO     MsgType = 6
	MsgType_MT_CUSTOM  MsgType = 7
)

var MsgType_name = map[int32]string{
	0: "MT_UNKNOWN",
	1: "MT_TEXT",
	2: "MT_EMOJI",
	3: "MT_VOICE",
	4: "MT_IMAGE",
	5: "MT_FILE",
	6: "MT_GEO",
	7: "MT_CUSTOM",
}

var MsgType_value = map[string]int32{
	"MT_UNKNOWN": 0,
	"MT_TEXT":    1,
	"MT_EMOJI":   2,
	"MT_VOICE":   3,
	"MT_IMAGE":   4,
	"MT_FILE":    5,
	"MT_GEO":     6,
	"MT_CUSTOM":  7,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type MsgStatus int32

const (
	MsgStatus_MS_UNKNOWN  MsgStatus = 0
	MsgStatus_MS_NORMAL   MsgStatus = 1
	MsgStatus_MS_WITHDRAW MsgStatus = 2
)

var MsgStatus_name = map[int32]string{
	0: "MS_UNKNOWN",
	1: "MS_NORMAL",
	2: "MS_WITHDRAW",
}

var MsgStatus_value = map[string]int32{
	"MS_UNKNOWN":  0,
	"MS_NORMAL":   1,
	"MS_WITHDRAW": 2,
}

func (x MsgStatus) String() string {
	return proto.EnumName(MsgStatus_name, int32(x))
}

func (MsgStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type Message struct {
	Id        int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SendId    int64     `protobuf:"varint,2,opt,name=sendId,proto3" json:"sendId,omitempty"`
	SessionId int64     `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Time      int64     `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	DeviceId  int64     `protobuf:"varint,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	RequestId int64     `protobuf:"varint,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Status    MsgStatus `protobuf:"varint,7,opt,name=status,proto3,enum=rpc.MsgStatus" json:"status,omitempty"`
	Type      MsgType   `protobuf:"varint,8,opt,name=type,proto3,enum=rpc.MsgType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Message_Text
	//	*Message_Emoji
	//	*Message_Voice
	//	*Message_Image
	//	*Message_File
	//	*Message_Geo
	//	*Message_Custom
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetSendId() int64 {
	if m != nil {
		return m.SendId
	}
	return 0
}

func (m *Message) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Message) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Message) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Message) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetStatus() MsgStatus {
	if m != nil {
		return m.Status
	}
	return MsgStatus_MS_UNKNOWN
}

func (m *Message) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_MT_UNKNOWN
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Text struct {
	Text *Words `protobuf:"bytes,9,opt,name=text,proto3,oneof"`
}

type Message_Emoji struct {
	Emoji *Emoji `protobuf:"bytes,10,opt,name=emoji,proto3,oneof"`
}

type Message_Voice struct {
	Voice *Voice `protobuf:"bytes,11,opt,name=voice,proto3,oneof"`
}

type Message_Image struct {
	Image *Image `protobuf:"bytes,12,opt,name=image,proto3,oneof"`
}

type Message_File struct {
	File *File `protobuf:"bytes,13,opt,name=file,proto3,oneof"`
}

type Message_Geo struct {
	Geo *Geo `protobuf:"bytes,14,opt,name=geo,proto3,oneof"`
}

type Message_Custom struct {
	Custom *Custom `protobuf:"bytes,15,opt,name=custom,proto3,oneof"`
}

func (*Message_Text) isMessage_Content() {}

func (*Message_Emoji) isMessage_Content() {}

func (*Message_Voice) isMessage_Content() {}

func (*Message_Image) isMessage_Content() {}

func (*Message_File) isMessage_Content() {}

func (*Message_Geo) isMessage_Content() {}

func (*Message_Custom) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetText() *Words {
	if x, ok := m.GetContent().(*Message_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Message) GetEmoji() *Emoji {
	if x, ok := m.GetContent().(*Message_Emoji); ok {
		return x.Emoji
	}
	return nil
}

func (m *Message) GetVoice() *Voice {
	if x, ok := m.GetContent().(*Message_Voice); ok {
		return x.Voice
	}
	return nil
}

func (m *Message) GetImage() *Image {
	if x, ok := m.GetContent().(*Message_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Message) GetFile() *File {
	if x, ok := m.GetContent().(*Message_File); ok {
		return x.File
	}
	return nil
}

func (m *Message) GetGeo() *Geo {
	if x, ok := m.GetContent().(*Message_Geo); ok {
		return x.Geo
	}
	return nil
}

func (m *Message) GetCustom() *Custom {
	if x, ok := m.GetContent().(*Message_Custom); ok {
		return x.Custom
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Text)(nil),
		(*Message_Emoji)(nil),
		(*Message_Voice)(nil),
		(*Message_Image)(nil),
		(*Message_File)(nil),
		(*Message_Geo)(nil),
		(*Message_Custom)(nil),
	}
}

type Words struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Words) Reset()         { *m = Words{} }
func (m *Words) String() string { return proto.CompactTextString(m) }
func (*Words) ProtoMessage()    {}
func (*Words) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Words) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Words.Unmarshal(m, b)
}
func (m *Words) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Words.Marshal(b, m, deterministic)
}
func (m *Words) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Words.Merge(m, src)
}
func (m *Words) XXX_Size() int {
	return xxx_messageInfo_Words.Size(m)
}
func (m *Words) XXX_DiscardUnknown() {
	xxx_messageInfo_Words.DiscardUnknown(m)
}

var xxx_messageInfo_Words proto.InternalMessageInfo

func (m *Words) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Emoji struct {
	FaceId               int64    `protobuf:"varint,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	FaceUrl              string   `protobuf:"bytes,2,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emoji) Reset()         { *m = Emoji{} }
func (m *Emoji) String() string { return proto.CompactTextString(m) }
func (*Emoji) ProtoMessage()    {}
func (*Emoji) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Emoji) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emoji.Unmarshal(m, b)
}
func (m *Emoji) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emoji.Marshal(b, m, deterministic)
}
func (m *Emoji) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emoji.Merge(m, src)
}
func (m *Emoji) XXX_Size() int {
	return xxx_messageInfo_Emoji.Size(m)
}
func (m *Emoji) XXX_DiscardUnknown() {
	xxx_messageInfo_Emoji.DiscardUnknown(m)
}

var xxx_messageInfo_Emoji proto.InternalMessageInfo

func (m *Emoji) GetFaceId() int64 {
	if m != nil {
		return m.FaceId
	}
	return 0
}

func (m *Emoji) GetFaceUrl() string {
	if m != nil {
		return m.FaceUrl
	}
	return ""
}

type Voice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Voice) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Voice) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

type File struct {
	Id                   int64    `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,14,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Geo struct {
	Desc                 string   `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geo) Reset()         { *m = Geo{} }
func (m *Geo) String() string { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()    {}
func (*Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geo.Unmarshal(m, b)
}
func (m *Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geo.Marshal(b, m, deterministic)
}
func (m *Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geo.Merge(m, src)
}
func (m *Geo) XXX_Size() int {
	return xxx_messageInfo_Geo.Size(m)
}
func (m *Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Geo proto.InternalMessageInfo

func (m *Geo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Geo) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Geo) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Custom struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (m *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(m, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

func (m *Custom) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("rpc.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("rpc.MsgStatus", MsgStatus_name, MsgStatus_value)
	proto.RegisterType((*Message)(nil), "rpc.Message")
	proto.RegisterType((*Words)(nil), "rpc.Words")
	proto.RegisterType((*Emoji)(nil), "rpc.Emoji")
	proto.RegisterType((*Voice)(nil), "rpc.Voice")
	proto.RegisterType((*Image)(nil), "rpc.Image")
	proto.RegisterType((*File)(nil), "rpc.File")
	proto.RegisterType((*Geo)(nil), "rpc.Geo")
	proto.RegisterType((*Custom)(nil), "rpc.Custom")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x93, 0xf8, 0x4f, 0xe2, 0x49, 0x9a, 0x5a, 0x2b, 0x04, 0x0b, 0x54, 0x22, 0x32, 0x02,
	0x55, 0x3d, 0xf4, 0x50, 0x8e, 0x15, 0x87, 0xb6, 0xa4, 0x89, 0xa1, 0x4e, 0x90, 0xe3, 0x36, 0xc0,
	0xc5, 0x72, 0xed, 0xad, 0xb3, 0x28, 0xb1, 0x83, 0x77, 0x53, 0x5a, 0xc4, 0xf3, 0xf2, 0x1c, 0x68,
	0xc7, 0xae, 0x1b, 0xa9, 0xb7, 0x99, 0xef, 0xfb, 0x79, 0x56, 0xb3, 0x33, 0x5e, 0xb0, 0x56, 0x22,
	0x3d, 0x5c, 0x17, 0xb9, 0xcc, 0x89, 0x56, 0xac, 0x63, 0xe7, 0x9f, 0x06, 0x6d, 0x8f, 0x09, 0x11,
	0xa5, 0x8c, 0xf4, 0xa1, 0xc5, 0x13, 0xda, 0x1c, 0x34, 0xf7, 0x35, 0xbf, 0xc5, 0x13, 0xf2, 0x1c,
	0x4c, 0xc1, 0xb2, 0xc4, 0x4d, 0x68, 0x0b, 0xb5, 0x2a, 0x23, 0x7b, 0x60, 0x09, 0x26, 0x04, 0xcf,
	0x33, 0x37, 0xa1, 0x1a, 0x5a, 0x8f, 0x02, 0x21, 0xa0, 0x4b, 0xbe, 0x62, 0x54, 0x47, 0x03, 0x63,
	0xf2, 0x0a, 0x3a, 0x09, 0xbb, 0xe5, 0x31, 0x73, 0x13, 0x6a, 0xa0, 0x5e, 0xe7, 0xaa, 0x5a, 0xc1,
	0x7e, 0x6d, 0x98, 0x90, 0x6e, 0x42, 0xcd, 0xb2, 0x5a, 0x2d, 0x90, 0xf7, 0x60, 0x0a, 0x19, 0xc9,
	0x8d, 0xa0, 0xed, 0x41, 0x73, 0xbf, 0x7f, 0xd4, 0x3f, 0x2c, 0xd6, 0xf1, 0xa1, 0x27, 0xd2, 0x19,
	0xaa, 0x7e, 0xe5, 0x92, 0x01, 0xe8, 0xf2, 0x7e, 0xcd, 0x68, 0x07, 0xa9, 0xde, 0x03, 0x15, 0xdc,
	0xaf, 0x99, 0x8f, 0x0e, 0x12, 0xec, 0x4e, 0x52, 0x6b, 0xd0, 0xdc, 0xef, 0x1e, 0x01, 0x12, 0xf3,
	0xbc, 0x48, 0xc4, 0xb8, 0xe1, 0xa3, 0x43, 0x1c, 0x30, 0xd8, 0x2a, 0xff, 0xc9, 0x29, 0x6c, 0x21,
	0x43, 0xa5, 0x8c, 0x1b, 0x7e, 0x69, 0x29, 0xe6, 0x36, 0xe7, 0x31, 0xa3, 0xdd, 0x2d, 0xe6, 0x4a,
	0x29, 0x8a, 0x41, 0x4b, 0x31, 0x7c, 0x15, 0xa5, 0x8c, 0xf6, 0xb6, 0x18, 0x57, 0x29, 0x8a, 0x41,
	0x8b, 0xbc, 0x01, 0xfd, 0x86, 0x2f, 0x19, 0xdd, 0x41, 0xc4, 0x42, 0xe4, 0x9c, 0x2f, 0x15, 0x81,
	0x06, 0xd9, 0x03, 0x2d, 0x65, 0x39, 0xed, 0xa3, 0xdf, 0x41, 0x7f, 0xc4, 0xf2, 0x71, 0xc3, 0x57,
	0x32, 0x79, 0x07, 0x66, 0xbc, 0x11, 0x32, 0x5f, 0xd1, 0x5d, 0x04, 0xba, 0x08, 0x9c, 0xa1, 0x34,
	0x6e, 0xf8, 0x95, 0x79, 0x6a, 0x41, 0x3b, 0xce, 0x33, 0xc9, 0x32, 0xe9, 0xbc, 0x06, 0x03, 0xbb,
	0xc5, 0xf9, 0xa8, 0x7b, 0x50, 0x73, 0xb6, 0xca, 0xce, 0x9d, 0x63, 0x30, 0xb0, 0x4f, 0xf2, 0x02,
	0xda, 0x37, 0x51, 0xcc, 0xc2, 0x7a, 0x0f, 0x4c, 0x95, 0xba, 0x09, 0x79, 0x09, 0x1d, 0x34, 0x36,
	0xc5, 0x12, 0xb7, 0xc1, 0xf2, 0x11, 0xbc, 0x2c, 0x96, 0xce, 0x77, 0x30, 0xf0, 0x02, 0xb6, 0xf6,
	0xc7, 0xc2, 0xfd, 0x21, 0xa0, 0x0b, 0xfe, 0x87, 0x21, 0x6f, 0xf8, 0x18, 0xe3, 0x26, 0x6c, 0x8a,
	0x48, 0xf2, 0x3c, 0xc3, 0xd5, 0x31, 0xfc, 0x3a, 0x27, 0x36, 0x68, 0xaa, 0xbc, 0x8e, 0x05, 0x54,
	0xe8, 0xfc, 0x05, 0x03, 0xef, 0xed, 0x49, 0xe9, 0x67, 0x60, 0xfc, 0xe6, 0x89, 0x5c, 0x54, 0xb5,
	0xcb, 0x44, 0x2d, 0xec, 0x82, 0xf1, 0x74, 0x21, 0xab, 0xd2, 0x55, 0xf6, 0xb4, 0x30, 0x79, 0x0b,
	0x3b, 0x72, 0xb1, 0x59, 0x5d, 0x67, 0x11, 0x5f, 0x62, 0x4f, 0x06, 0x7a, 0xbd, 0x5a, 0x54, 0x8d,
	0x7d, 0x05, 0x5d, 0x8d, 0xa4, 0x3a, 0xbc, 0x57, 0xff, 0x17, 0x04, 0xf4, 0x2c, 0x5a, 0x95, 0xb3,
	0xb3, 0x7c, 0x8c, 0xeb, 0x5e, 0xfb, 0xe5, 0xd6, 0x63, 0xaf, 0xd5, 0xb1, 0xbb, 0x8f, 0xfd, 0x7c,
	0x04, 0x6d, 0xc4, 0x72, 0x05, 0x27, 0x4c, 0xc4, 0x0f, 0x23, 0x50, 0xb1, 0x82, 0x97, 0x91, 0xc4,
	0x7e, 0x9a, 0xbe, 0x0a, 0x51, 0xc9, 0x52, 0x6c, 0x45, 0x29, 0x59, 0xea, 0x38, 0x60, 0x96, 0x23,
	0x26, 0xb4, 0x1e, 0x6c, 0x55, 0xe4, 0x21, 0x3d, 0xb8, 0x83, 0x76, 0xb5, 0xf7, 0xa4, 0x0f, 0xe0,
	0x05, 0xe1, 0xe5, 0xe4, 0xcb, 0x64, 0x3a, 0x9f, 0xd8, 0x0d, 0xd2, 0x85, 0xb6, 0x17, 0x84, 0xc1,
	0xf0, 0x5b, 0x60, 0x37, 0x49, 0x0f, 0x3a, 0x5e, 0x10, 0x0e, 0xbd, 0xe9, 0x67, 0xd7, 0x6e, 0x55,
	0xd9, 0xd5, 0xd4, 0x3d, 0x1b, 0xda, 0x5a, 0x95, 0xb9, 0xde, 0xc9, 0x68, 0x68, 0xeb, 0xd5, 0x67,
	0xe7, 0xee, 0xc5, 0xd0, 0x36, 0x08, 0x80, 0xe9, 0x05, 0xe1, 0x68, 0x38, 0xb5, 0x4d, 0xb2, 0x03,
	0x96, 0x17, 0x84, 0x67, 0x97, 0xb3, 0x60, 0xea, 0xd9, 0xed, 0x83, 0x63, 0xb0, 0xea, 0xff, 0x12,
	0xcf, 0x9e, 0x6d, 0x9d, 0xad, 0xd8, 0x59, 0x38, 0x99, 0xfa, 0xde, 0xc9, 0x85, 0xdd, 0x24, 0xbb,
	0xd0, 0xf5, 0x66, 0xe1, 0xdc, 0x0d, 0xc6, 0x9f, 0xfc, 0x93, 0xb9, 0xdd, 0x3a, 0x35, 0x7e, 0xa8,
	0xe7, 0xe8, 0xda, 0xc4, 0xa7, 0xe9, 0xc3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x16, 0x88,
	0xb0, 0xa7, 0x04, 0x00, 0x00,
}
