// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pack.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PackType int32

const (
	PackType_PT_UNKNOWN      PackType = 0
	PackType_PT_AUTH         PackType = 1
	PackType_PT_MSG          PackType = 2
	PackType_PT_HEARTBEAT    PackType = 3
	PackType_PT_DETECT       PackType = 4
	PackType_PT_ACTION       PackType = 5
	PackType_PT_NOTIFICATION PackType = 6
	PackType_PT_ACK          PackType = 7
)

var PackType_name = map[int32]string{
	0: "PT_UNKNOWN",
	1: "PT_AUTH",
	2: "PT_MSG",
	3: "PT_HEARTBEAT",
	4: "PT_DETECT",
	5: "PT_ACTION",
	6: "PT_NOTIFICATION",
	7: "PT_ACK",
}

var PackType_value = map[string]int32{
	"PT_UNKNOWN":      0,
	"PT_AUTH":         1,
	"PT_MSG":          2,
	"PT_HEARTBEAT":    3,
	"PT_DETECT":       4,
	"PT_ACTION":       5,
	"PT_NOTIFICATION": 6,
	"PT_ACK":          7,
}

func (x PackType) String() string {
	return proto.EnumName(PackType_name, int32(x))
}

func (PackType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3827fe073a5f7620, []int{0}
}

type Input struct {
	Type                 PackType `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.PackType" json:"type,omitempty"`
	RequestId            int64    `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_3827fe073a5f7620, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetType() PackType {
	if m != nil {
		return m.Type
	}
	return PackType_PT_UNKNOWN
}

func (m *Input) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Input) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Output struct {
	Type                 PackType `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.PackType" json:"type,omitempty"`
	RequestId            int64    `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_3827fe073a5f7620, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetType() PackType {
	if m != nil {
		return m.Type
	}
	return PackType_PT_UNKNOWN
}

func (m *Output) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Output) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Output) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.PackType", PackType_name, PackType_value)
	proto.RegisterType((*Input)(nil), "rpc.Input")
	proto.RegisterType((*Output)(nil), "rpc.Output")
}

func init() { proto.RegisterFile("pack.proto", fileDescriptor_3827fe073a5f7620) }

var fileDescriptor_3827fe073a5f7620 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xbf, 0x69, 0x7e, 0xfa, 0xf5, 0xd8, 0xd6, 0x61, 0xdc, 0x64, 0x23, 0xc4, 0xae, 0x82,
	0x8b, 0x2c, 0xf4, 0x0a, 0xa6, 0x31, 0xda, 0x50, 0x4c, 0x86, 0xf1, 0x14, 0x41, 0x90, 0x21, 0x26,
	0x11, 0x4a, 0xa1, 0x19, 0xe3, 0x64, 0xd1, 0xbd, 0x78, 0xdd, 0xd2, 0x21, 0xea, 0x0d, 0xb8, 0x7b,
	0xe7, 0x19, 0x38, 0xcf, 0xcb, 0x39, 0x00, 0xba, 0xac, 0x76, 0xb1, 0xee, 0x5a, 0xd3, 0x32, 0xa7,
	0xd3, 0xd5, 0xe2, 0x19, 0xbc, 0x6c, 0xaf, 0x7b, 0xc3, 0x2e, 0xc0, 0x35, 0x07, 0xdd, 0x04, 0x24,
	0x24, 0xd1, 0xfc, 0x6a, 0x16, 0x77, 0xba, 0x8a, 0x45, 0x59, 0xed, 0xf0, 0xa0, 0x1b, 0x69, 0xbf,
	0xd8, 0x39, 0x40, 0xd7, 0xbc, 0xf5, 0xcd, 0xbb, 0x51, 0xdb, 0x3a, 0x18, 0x85, 0x24, 0x72, 0xe4,
	0x64, 0x20, 0x59, 0xcd, 0x18, 0xb8, 0x75, 0x69, 0xca, 0xc0, 0x09, 0x49, 0x34, 0x95, 0x36, 0x2f,
	0x3e, 0x09, 0xf8, 0x45, 0x6f, 0xfe, 0x4c, 0x50, 0xb5, 0x75, 0x63, 0x05, 0x9e, 0xb4, 0xf9, 0xc8,
	0xb6, 0xfb, 0xd7, 0x36, 0x70, 0x43, 0x12, 0x4d, 0xa4, 0xcd, 0x3f, 0x45, 0xbc, 0xdf, 0x22, 0x97,
	0x1f, 0x04, 0xfe, 0x7f, 0xdb, 0xd8, 0x1c, 0x40, 0xa0, 0xda, 0xe4, 0xeb, 0xbc, 0x78, 0xcc, 0xe9,
	0x3f, 0x76, 0x02, 0x63, 0x81, 0x8a, 0x6f, 0x70, 0x45, 0x09, 0x03, 0xf0, 0x05, 0xaa, 0xfb, 0x87,
	0x3b, 0x3a, 0x62, 0x14, 0xa6, 0x02, 0xd5, 0x2a, 0xe5, 0x12, 0x97, 0x29, 0x47, 0xea, 0xb0, 0x19,
	0x4c, 0x04, 0xaa, 0x9b, 0x14, 0xd3, 0x04, 0xa9, 0x3b, 0x3c, 0x79, 0x82, 0x59, 0x91, 0x53, 0x8f,
	0x9d, 0xc1, 0xa9, 0x40, 0x95, 0x17, 0x98, 0xdd, 0x66, 0x09, 0xb7, 0xd0, 0x1f, 0x06, 0xf2, 0x64,
	0x4d, 0xc7, 0x4b, 0xef, 0xe9, 0xb8, 0xf5, 0x17, 0xdf, 0x5e, 0xe0, 0xfa, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x6c, 0xaf, 0x4c, 0x8c, 0x8f, 0x01, 0x00, 0x00,
}
